/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Wed Dec 11 13:12:17 2013
 * Do Not Modify the File.
 */

#ifndef __CUST__
#define __CUST__

#define CUST_EINT_TOUCH_PANEL_NUM              5

#define GPIO_CTP_EINT_PIN         GPIO25
#define GPIO_CTP_EN_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CTP_EN_PIN_M_EINT   GPIO_MODE_02
#define GPIO_CTP_EN_PIN_M_LPD   GPIO_MODE_01
#define GPIO_CTP_EN_PIN_M_DPI_G   GPIO_MODE_04
#define GPIO_CTP_EN_PIN_M_DBG_OUT   GPIO_MODE_06
#define GPIO_CTP_EN_PIN_M_CONN_GPIO   GPIO_MODE_07
#define GPIO_CTP_EINT_PIN_M_EINT   GPIO_MODE_02


#define GPIO_CTP_RST_PIN         GPIO105
#define GPIO_CTP_RST_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CTP_RST_PIN_M_SCL   GPIO_MODE_01


/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */



#endif /* __CUST__ */


